"""add google_id and make password_hash nullable

Revision ID: 2e101a5919fc
Revises: c4d5e6f7a8b9
Create Date: 2026-09-25 17:12:54.695992

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e101a5919fc"
down_revision: str | Sequence[str] | None = "c4d5e6f7a8b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_unique_constraint("uq_users_google_id", "users", ["google_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("uq_users_google_id", "users", type_="unique")
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
